- hosts: all
  sudo: yes
  tasks:
  - name: setup network
    copy: src=interfaces dest=/etc/network/interfaces
  - name: restart network
    service: name=networking state=restarted
  - name: install openvpn
    apt: name=openvpn state=latest
  - name: install bridge-utils
    apt: name=bridge-utils state=latest
  - name: enable ip forwarding
    sysctl: name=net.ipv4.ip_forward value=1 reload=yes
  - name: vpn config 1
    copy: src=laptop.conf dest=/etc/openvpn/laptop.conf
  - name: vpn config 2
    copy: src=keys dest=/etc/openvpn directory_mode=0700 mode=0600
  - name: start vpn
    service: name=openvpn state=restarted
    
